### PR TITLE
renamed tb forlder to test_program #229

### PR DESCRIPTION
**Pull request by davideschiavone**
Renamed the tb folder to test_program

### CODE REVIEW

**Comment by bluewww** [comment]
I mean if the name is a problem I would suggest to just call it 'example'. It is not a testbench anymore, just an example. Then you can also write in the README that this subdirectory is only for demonstration purposes.

My personal take on testing philosphy: It is a matter of the process. Mention multiple times in the README that people need to use core verif. Require people to add a test that covers the changes/feature. Require all CI to pass. Enforce code style and review. Demand big PR be split up etc. I dont think naming things a certain way is too important.

**Comment by davideschiavone** [comment]
I do agree with @bluewww , it's not  a folder for `testing` or `verification`. 
It's just an example to let the users try out the core.
Also other cores have a directory where you can run Hello world. It does not mean your are testing it. We can call it example if it is better.

**Comment by MikeOpenHWGroup** [comment]
> if the name is a problem I would suggest to just call it 'example'.

The name is not really the problem.  The concern is the existence of an unsanctioned testbench which discourages use of the real testbench by RTL Contributors.

> It is not a testbench anymore, just an example. Then you can also write in the README that this subdirectory is only for demonstration purposes.

The [core](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/tb/core) testbench in [core-v-verif](https://github.com/openhwgroup/core-v-verif), and associated [README](https://github.com/openhwgroup/core-v-verif/blob/master/cv32/sim/core/README.md) in the `cv32/sim/core` directory should provide a simple example for Contributors to the CV32E40 RTL.

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone  Unfortunately this PR has been laying around for a very long (much too long) time and it is now completely outdated. Could you please either remove the pull request or issue a new one with changes that are still relevant?

**Comment by davideschiavone** [comment]
Sure! Thanks for reminding it.

**Pull request closed without merging**
