### PR TITLE
Aligned all RTL/BHV files headers with correct date, contributors and Solderpad Hardware License v2.1

### PR DESCRIPTION
**Pull request by pascalgouedo**
Used latest Solderpad Hardware License v2.1 defined in Appendix [here](http://solderpad.org/licenses/SHL-2.1/).

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
@pascalgouedo , my current understanding is that:
1. Any file that is meaningfully modified under a preexisting license should have a new copyright declared by the contributor or contributor's organization and the preexisting copyright and license must be preserved.
2. The current advice from Eclipse is that legally, the only year in the copyright header should be the year that the content was created.
3. Files must retain the header of the original, whether they are substantially modified or split into multiple files.

If we follow the above, then much of this PR is not required, and my recommendation would be to simply preprend a new copyright to each file you have modified:
```
// Copyright (c) 2024 Dolphin Design
```

**Comment by pascalgouedo** [comment]
And what about SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1 ?

If I don't add it all files stays with 2.0 license

**Comment by pascalgouedo** [comment]
Is this example ok ?

// Copyright 2024 OpenHW Group and Dolphin Design
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
//
// Copyright 2020 Silicon Labs, Inc.
//
// This file, and derivatives thereof are licensed under the
// Solderpad License, Version 2.0 (the "License").
//
// Use of this file means you agree to the terms and conditions
// of the license and are in full compliance with the License.
//
// You may obtain a copy of the License at:
//
//     https://solderpad.org/licenses/SHL-2.0/
//
// Unless required by applicable law or agreed to in writing, software
// and hardware implementations thereof distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED.
//
// See the License for the specific language governing permissions and
// limitations under the License.

**Comment by MikeOpenHWGroup** [comment]
> And what about SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1 ?
> If I don't add it all files stays with 2.0 license

Yes, that is my understanding.  When you joined the project, most of the files were licensed under Solderpad 2.0.  If these files have not changed, they can remain licensed under SHL-2.0.  We _can_ update the license, but we are not required to.

...at least, that is my understanding...

**Comment by pascalgouedo** [comment]
> > And what about SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1 ?
> > If I don't add it all files stays with 2.0 license
> 
> Yes, that is my understanding. When you joined the project, most of the files were licensed under Solderpad 2.0. If these files have not changed, they can remain licensed under SHL-2.0. We _can_ update the license, but we are not required to.
> 
> ...at least, that is my understanding...

Quite hard to figure out which files have changed and which that haven't after more than a year of development ...

**Comment by pascalgouedo** [comment]
A lot of headers have already been changed since v1.
I have to restore all v1 headers and add copyright and correct license if needed?
If this is the case it will be quite cumbersome I will never be able to freeze this week.

**Comment by pascalgouedo** [comment]
What I can see is that nearly all files changed, at least because of verible usage.

**Comment by MikeOpenHWGroup** [comment]
> What I can see is that nearly all files changed, at least because of verible usage.

True enough.  Then I suggest the following is sufficient:
```
// Copyright (c) 2024 OpenHW Group and Dolphin Design
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
```

**Comment by DBees** [comment]
guys trying to follow the chain here. Are we proposing to up-version the license to SHL-2.1 from SHL-2.0 and change the copyright statement to 2024 on code that was authored by others? I don't think we can do that but I may misunderstand what's being proposed @MikeOpenHWGroup @pascalgouedo

**Comment by MikeOpenHWGroup** [comment]
No, we are explicitly not doing that.  My recommendation is that we should
not modify the license header on files that have not been modified, or with
minor modifications.  Pascal has pointed out that many files have had
substantial modifications, so it makes sense to update the copyright
statement.

**Comment by DBees** [comment]
Right but who modified the files? If not the original author you could add a new copyright statement/date by the additional new author.

**Comment by Floadv298** [comment]
To my understanding only files touched, should get an updated license and copyright but we may need to check with some legal experts.
Agree with Duncan, the original author can easily update the copyright.
Can we discuss this at the E40Pv2 Verification meeting today at 1pm Paris time?

**Comment by pascalgouedo** [comment]
> Everyone should read the Eclipse [Legal Documentation Requirements](https://www.eclipse.org/projects/handbook/#legaldoc), especially the associated [FAQ](https://www.eclipse.org/projects/handbook/#legaldoc-faq).
> 
> My interpretation is that the only change we _need_ to make to any files we modify is to declare the copywrite holder of the changes. Adding this one-liner to the top of the file is all we need:
> 
> ```
> // Copyright (c) {year} {owner}
> ```
> 
> We _could_ do more, but that is all that is _required_.

This is talking about Eclipse Public License, not Solderpad Hardware License.
And the (c) is nowhere else in any other license text I saw.

**Comment by MikeOpenHWGroup** [comment]
> This is talking about Eclipse Public License, not Solderpad Hardware License.

As OpenHW Group CORE-V repositories are governed by EF I think this document applies.  I could not find anything in Solderpad that contradicts these guidelines.

> And the (c) is nowhere else in any other license text I saw.

Maybe it is a North American thing.  Consider it optional.

**Pull request closed without merging**
