### PR TITLE
:bug: tracer for fence instructions #255

### PR DESCRIPTION
**Pull request by davideschiavone**
Fixing issue "Tracer does not log fence.i instruction #255"

### CODE REVIEW

**Comment by davideschiavone** [comment]
@imperas can you please double check if this solves your issue?

**Comment by Imperas** [comment]
@GTumbush 
Greg, I think you should probably take first look at this

**Comment by GTumbush** [comment]
What application do I run to test the fence instruction?

**Comment by Imperas** [comment]
Ah, good question, this was the example from the google generator
I changed the hello.c example to add the following inline assembler
in the old tracer, this causes it to get out of sync

> int main () {
>     *asm("fence.i\n");*
>     printf("Hello World\n");
> }

That should be enough to show if the tracer is fixed

Thx
Lee

**Comment by GTumbush** [comment]
I added asm("fence.i\n"); to hello.c and ran it against the fix255 code (cloned with git clone -b fix255 https://github.com/davideschiavone/riscv.git) and the hello test now passes with no miscompares.    The RTL treats fence as a no-op. The issue appears to be solved. Imperas, please close if you agree.

**Comment by Imperas** [comment]
@davideschiavone @GTumbush 
Looks like this has solved the issue with the fence instructions not being traced - great.

Are you any further forward with the issues regarding CSR values at certain instructions and exceptions ?
Thx
Lee

**Comment by GTumbush** [comment]
There have been commits but none have fixed the CSR issue reported in https://github.com/openhwgroup/cv32e40p/issues/256

**Comment by davideschiavone** [comment]
I consider this issue closed then and we will focus on #256

**Pull request merged**
