### PR TITLE
Updates to the HPM for openhwgroup/cv32e40p#432

### PR DESCRIPTION
**Pull request by jm4rtin**
Includes:
* Unprivileged read-only shadow registers for the HPM
* Removal of mcounteren from machine mode only (PULP_SECURE=0)
* Implementation of mcounteren for user mode (PULP_SECURE=1)

This is for #432 and #448. Related documentation change: openhwgroup/core-v-docs#168

Change-Id: Ia2641b5d9670c872e22b3b805a378f339cf1331d
Signed-off-by: John Eric Martin <John.Martin@emmicro-us.com>

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
For what its worth, this PR survives a MetricsCI regression.

**Review by Silabs-ArjanB — APPROVED** [review]

**Comment by Silabs-ArjanB** [comment]
Hi @jm4rtin Could you please resolve above conflicts and then we can get this one merged next.

**Comment by jm4rtin** [comment]
@Silabs-ArjanB Done.

**Comment by Silabs-ArjanB** [comment]
Thanks

**Pull request merged**
