### PR TITLE
Moved CLINTx CSR addresses to custom space #253

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

### CODE REVIEW

**Comment by davideschiavone** [comment]
Hi @Silabs-ArjanB , thanks a lot for the fix. Can you also update the the tb/core/ examples?

For instance, the crt0.s ues 0x306 as address
https://github.com/openhwgroup/cv32e40p/blob/master/tb/core/custom/crt0.S#L33

or the interrupt tests uses 307 for the MIPX.

Thanks a lot,
Davide

**Comment by Silabs-ArjanB** [comment]
Of course, I didn't realize there was a test. Where do you normally run this test from (directly in the cv32e40p repos somehow or from core-v-verif)?

**Comment by davideschiavone** [comment]
Ther are in the CV32e40p repo now but @MikeOpenHWGroup  is moving them to the core-verif for what concern the interrupt test. The custom folder only contains an hello world example and it will stay there as it is not a test. Indeed the tb directory will also change the name as it's not a "test" bench anymore.

**Comment by Silabs-ArjanB** [comment]
Updated the assembly files now

**Comment by vogelpi** [comment]
Thanks @davideschiavone for keeping me in the loop!

**Pull request merged**
