### PR TITLE
Riviera-PRO support

### PR DESCRIPTION
**Pull request by dawidzim**
Hey!
This is a patch which added support for Riviera-PRO simulator.

### CODE REVIEW

**Review by Silabs-ArjanB — COMMENTED** [review]
No ifdefs are allowed in the RTL. Cannot accept this. What is 'wrong' with the FIFO RTL?

**Comment by dawidzim** [comment]
Hey @Silabs-ArjanB 
I remove `ifdef`. What you think now about this?

**Comment by Silabs-ArjanB** [comment]
Hi @dawidzim You also removed the 'unique' keyword. Can you explain what is wrong with the original code please?

**Comment by dawidzim** [comment]
With code is all fine. But Riviera-PRO 2020.04 has problem with this fragment

**Comment by Silabs-ArjanB** [comment]
Hi @dawidzim I discussed with @davideschiavone and we would like to keep this repos as simple as possible, specifically not adding back in support for more simulators. We do however appreciate your work and we aim to support as many simulators as possible. The right place for extending simulator support for this core would be in core-v-verif (and I see that you did a pull request there as well). Also, in general, we do not intend to update the RTL for each simulator work-around, so ideally the issue you mentioned gets fixed in the simulator itself.

**Pull request closed without merging**
