### PR TITLE
Create new Makefile to clone the fpnew directory in rtl/fpnew

### PR DESCRIPTION
**Pull request by lucabertaccini**

### CODE REVIEW

**Comment by davideschiavone** [comment]
Hi @MikeOpenHWGroup ,

@lucabertaccini is a new PhD student at ETH Zurich, this PR should solve this issue

https://github.com/openhwgroup/cv32e40p/issues/260

Let us know what you think.
Best
Davide

**Comment by davideschiavone** [comment]
@lucabertaccini , can you please re-do the changes in 
tb/verilator-model/Makefile ?

You made many "not needed" modifications as replacing spacing with tabs (probably due to some setting in sublime for instance)

It also does not work.

**Comment by lucabertaccini** [comment]
@davideschiavone, I uploaded the required modifications using a "git push -f"

**Comment by davideschiavone** [comment]
Hi @MikeOpenHWGroup ! Thanks for your input, in my opinion this should be handled in a differen PR. Can you open another issue for this? This PR should simply solve the FPU dependency. If you agree, I merge this and then we address the manifest rule in the Makefile in another PR

**Pull request merged**
