### PR TITLE
Addition of changelog

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

### CODE REVIEW

**Review by davideschiavone — CHANGES_REQUESTED** [review]
add in the README and/or Documentation the rule for tagging PRs

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone I updated the readme file. Could you plese give it another look?

**Review by davideschiavone — APPROVED** [review]

**Comment by davideschiavone** [comment]
LGTM

@pascalgouedo tagging Pascal to make him aware of this

**Comment by davideschiavone** [comment]
LGTM

@pascalgouedo tagging Pascal to make him aware of this

**Pull request merged**
