### PR TITLE
vendorized fpu

### PR DESCRIPTION
**Pull request by davideschiavone**
Added local copy of FPU and sub dependencies

### CODE REVIEW

**Comment by davideschiavone** [comment]
The manifest file should be updated in a second PR - suggestions needed

**Review by Silabs-ArjanB — COMMENTED** [review]
Why can't the FPU be put into its own repos? I don't think it belongs in the cv32e40p repos.

**Comment by pascalgouedo** [comment]
Hi
To keep coherency with core-v-mcu and have all rtl in the same place, maybe it is better to put vendor directory in rtl.

**Review by Silabs-ArjanB — APPROVED** [review]

**Comment by davideschiavone** [comment]
thanks - waiting for @MikeOpenHWGroup

**Review by MikeOpenHWGroup — APPROVED** [review]

**Pull request merged**
