### PR TITLE
Add non-vectorized IRQ mode

### PR DESCRIPTION
**Pull request by zetalog**
This patch adds a non-vectorized IRQ mode. When it is configured,
CPU fetches the same entry of MTVEC as exceptions upon IRQ
arrivals. This allows us to try non-vectorized IRQ based software
without the need to modify it.

Tested in a VCS simulation environment.

Signed-off-by: Lv Zheng <zhenglv@hotmail.com>

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @zetalog, I am Mike Thompson, verification lead for this project.  Thanks for your contribution.  We have had an off-line discussion about it and I will let @davideschiavone respond formally.   For now I have two requests:
1. Your PR comes with no documentation. Can you either update the current documentation (in [core-v-docs](https://github.com/openhwgroup/core-v-docs/tree/master/cores/cv32e40p)), or open an issue there to add the new feature to the documentation?
2. The verification environment for this core is in the [core-v-verif](https://github.com/openhwgroup/core-v-verif) repository.  Would you be willing to integrate your updates and testcases to that repo?  I can help you with that.

**Comment by davideschiavone** [comment]
Hello @zetalog 

Your PR is really appreciated. Adding to what @MikeOpenHWGroup said, I prefer if you open an issue on the documentation side as we are going to rewrite it text based.


Regarding the technical work per se, would you mind to make the MTVEC and MTVECx writable so that instead of defines you can actually use this features at runtime?

Thanks a lot
Davide

**Comment by zetalog** [comment]
Hi, Thanks for the review.
>  Can you either update the current documentation (in core-v-docs), or open an issue there to add the new feature to the documentation?

I'm trying to figure out if I can add the documentation changes myself, or I'll just open an issue.

> The verification environment for this core is in the core-v-verif repository. Would you be willing to integrate your updates and testcases to that repo? I can help you with that.

I had a different verification bench than core-v-verif. My testcase is an opensbi + Linux smp combined program, you can find it here:
https://github.com/zetalog/sdfirm
The easiest way to try it is:
$ export SUBARCH=riscv
$ export CROSS_COMPILE=riscv...-
$ make spike_rv64_defconfig
$ make
$ spike -p 4 ./sdfirm
It supports several boards/models including some that are shipped with CV32E.
As you know, most of the opensbi features are implemented without the support of vectorized IRQ, so I hacked the CV32E RTL to get it run for some models.
The "sdfirm" project is not stable, the only user is me, I'm not able to maintain so many BSPs without any breakage. Especially I don't have most of the boards on my hand now.
I've already started to support core-v-verif here: https://github.com/zetalog/sdfirm/commit/677389e9, and it is not working right now.
When it is ready, I'll send you a pull request for core-v-verif, and you can decide if it is useful then.

Cheers

**Comment by zetalog** [comment]
> I prefer if you open an issue on the documentation side as we are going to rewrite it text based.

Sure.

> would you mind to make the MTVEC and MTVECx writable so that instead of defines you can actually use this features at runtime?

Sounds good to me, I'll give it a try.

**Comment by zetalog** [comment]
I updated the commit, tested it in my environment. It also passed core-v-verif hello-world-veri-run.
IMO,  the vector mode indication flag need also be added to the core-v-verif the existing tests.

The documentation change request can be found here:
https://github.com/openhwgroup/core-v-docs/issues/28

**Comment by zetalog** [comment]
> shouldn't it be 2bits?
My bad, will update the PR after doing a test.

BR
Lv

**Comment by zetalog** [comment]
Hi, Davide

Did you still see any problem?
Can I add Reviewed-by to the commit?

BTW, how can I pass the eclipsefdn/eca check?

Thanks and best regards
Lv

**Comment by davideschiavone** [comment]
Hello @zetalog ,

thanks it looks correct! I will give it a trial for test in these days and then merge!

For having the Eclipse check passing you should be a member of the OpenHW Group.

Maybe you are interest to be part of us? It would be amazing.

Adding @rickoco (CEO of OpenHW Group) to the conversation to link the two of you!

Best

**Comment by davideschiavone** [comment]
Thanks @Silabs-ArjanB and @zetalog .

Indeed it would be nice to have the `tvec_mode_q `and the missing `tvec_mode_q`.

Also, I was trying the code but I've seen that this register is only writable when PULP_SECURE=1.

May you please also add this register for PULP_SECURE=0 ? I would be great.

Best regards,
Davide

**Comment by zetalog** [comment]
> thanks it looks correct! I will give it a trial for test in these days and then merge!

Great!
My related testing code is here:
Non-VIRQ controlling: https://github.com/zetalog/sdfirm/blob/master/arch/riscv/include/asm/irqc.h
VIRQ controlling: https://github.com/zetalog/sdfirm/blob/master/arch/riscv/include/asm/ri5cy_firq.h
Handlers (Non-VIRQ at the beginning, and VIRQ at the end of the file):
https://github.com/zetalog/sdfirm/blob/master/arch/riscv/common/entry.S

I have 2 screenshots related to the test result and is trying to find a way to post them here.

> For having the Eclipse check passing you should be a member of the OpenHW Group.
> Maybe you are interest to be part of us? It would be amazing.
> Adding @rickoco (CEO of OpenHW Group) to the conversation to link the two of you!

Of course it's my great honor to be able to help open source RISCV.
I'm an individual contributor, willing to help doing some open source IC verification.

**Comment by zetalog** [comment]
> Indeed it would be nice to have the tvec_mode_q and the missing tvecx_mode_q.

Referring to my driver, https://github.com/zetalog/sdfirm/blob/master/arch/riscv/include/asm/ri5cy_firq.h

IMO, if we have IRQs vectorized, and removing external IRQ multipexing chip like PLIC, we'll be bounded due to too few bits of xIP/xIE registers.
And some SoCs may require to having more external IRQs lines.
That's why we have MIPX and MIEX to add 32 more bits of IRQ lines.

So I treats MTVECX as an extension to the MTVEC to have more external IRQs vectorized.
Should they have unified configuration?

Thanks and best regards

**Comment by zetalog** [comment]
non-virq
virq

**Comment by zetalog** [comment]
Can the images be seen there? I cannot view the images here.
The first image is a configuration of having CONFIG_RISCV_VIRQ=n in sdfirm.
And we can see timer IRQs arrived via 0x06000700 address which is a unified IRQ entry.
The second image is a configuration of having CONFIG_RISCV_VIRQ=y in sdfirm.
And we can see timer IRQs arrived via 0x0600471C address which is a vectorized IRQ entry.

**Comment by zetalog** [comment]
BTW, will CV32E add trap delegation registers?
It sounds reasonable to having MEDELEG and MIDELEG in a secure AEE environment.

**Comment by davideschiavone** [comment]
> 
> 
> > Indeed it would be nice to have the tvec_mode_q and the missing tvecx_mode_q.
> 
> Referring to my driver, https://github.com/zetalog/sdfirm/blob/master/arch/riscv/include/asm/ri5cy_firq.h
> 
> Correct me if I'm wrong.
> IMO, if we have IRQs vectorized, and removing external IRQ multipexing chip like PLIC, we'll be bounded due to too few bits of xIP/xIE registers.
> And some SoCs may require to have more external IRQs lines.
> That's why we have MIPX and MIEX to add 32 more bits of IRQ lines.
> So I treat MTVECX as an extension to the MTVEC to have more external IRQs vectorized.
> Should they have unified configuration?
> 
> Is this understanding correct?
> 
> Thanks and best regards

Hello, it is correct that we added MIPX and MIEX to extend to more interrupts lines, but we want to give SW the freedom to place (if used at all) the custom interrupt vector table wherever. That's why MTVECX. The are cases where one may use only the standard interrupts and other cases where one wants to use only the custom one (MTVECX). That's why we would like to have the vec_mode in both MTVEC and MTVEX indipendently. 

> BTW, will CV32E add trap delegation registers?

Ad the moment they are not planned for the CV32E40P, but they may be added in the next versions of embedded class 32b cores.

If you would like to be a member, you can sign up the Eclipse Contributor Agreement (ECA) and have an Eclipse Account.
You can create an account here: https://www.openhwgroup.org/register/
and sign off the Eclipse Contributor Agreement.  The OpenHW Group leverages the proven Eclipse Development Process for how we govern our open source projects.  

Use your github id whenever possible :)
best
Davide

**Comment by zetalog** [comment]
> There are cases where one may use only the standard interrupts and other cases where one wants to use only the custom one (MTVECX). That's why we would like to have the vec_mode in both MTVEC and MTVEX independently.

Should UTVEC have an independent vec_mode of MTVEC?

> If you would like to be a member, you can sign up the Eclipse Contributor Agreement (ECA) and have an Eclipse Account.

It works for me now, thanks!

**Comment by davideschiavone** [comment]
Yes utvec should have it different from mtvec but is ok to leave it like it is today as the security feature is not really maintained. So in my opinion you can leave it as it is. What do you think @Silabs-ArjanB ?

**Comment by Silabs-ArjanB** [comment]
utvec should be completely separate from mtvec indeed (but in CV32E40P User mode will not be present, so there is no need to do this now (just file a ticket for a future time if there currently still is sharing between these two registers or fix it right away)

**Comment by zetalog** [comment]
@davideschiavone @Silabs-ArjanB Thanks for the explanation. I'll update the change after performing a full functional test.

**Comment by zetalog** [comment]
I've been busy these days and didn't have time to response.
Thanks for the merge.

As promised, I've prepared a PR for core-v-verif.
It's up to you guys if it is useful and can be merged:
https://github.com/openhwgroup/core-v-verif/pull/166

**Pull request merged**
