### PR TITLE
Debug exception

### PR DESCRIPTION
**Pull request by silabs-PaulZ**
Fixes issue #185 

Handle exceptions during Debug Mode. CSR and status will not be updated during exceptions. This pull request will also add dm_exception_addr_i port to top-level, which provides the address to jump to when an exception occurs during Debug Mode.

This PR should be done after PR #339 

Related to documentation pull request:
https://github.com/openhwgroup/core-v-docs/pull/63

A verification pull request will be needed to fix the top-level connection.

### CODE REVIEW

**Comment by jm4rtin** [comment]
Aside from the need to re-merge this change is this PR ready? Would this need some change to the pulp DM (if using this implementation) as well (to flag the cmderr=3 during program buffer execution)?

**Comment by silabs-PaulZ** [comment]
Hi @jm4rtin , I believe this is handled in the puplp from code: https://github.com/pulp-platform/riscv-dbg/blob/834853c0c68fc48d032a3e256e563f2b0bd28492/debug_rom/debug_rom.S#L71-L74

@davideschiavone , can we get this PR merged in fairly soon?

**Comment by jm4rtin** [comment]
Hi @silabs-PaulZ , you are right. I have done a manual merge into our internal core and it resolves the issues we have. It needs to be merged with/rebased onto master to resolve the conflicts but otherwise it looks okay from my side.

**Comment by davideschiavone** [comment]
Yes @silabs-PaulZ , I wrote you an email, probably it got lost. Can you fix the conflicts? then I can merge

**Comment by silabs-PaulZ** [comment]
Hi @davideschiavone , I did a rebase and pushed.

**Comment by davideschiavone** [comment]
Can you please re-do it? @silabs-PaulZ , sorry for the incoveniece but the core is changing so rapidly.... :)

**Pull request merged**
