### PR TITLE
Cleaned up undriven signals and inferred latch (trap_base_addr)

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

Added 0 assignments to many signals that became undriven due to our chosen configuration. Also prevented latch generation on trap_base_addr (in IF stage) by adding default 0 assignment.

### CODE REVIEW

**Comment by davideschiavone** [comment]
Hello @Silabs-ArjanB , any comment on this?

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone , I am not sure what type of comment from me you are looking for. I made the pull request and I do not see any further questions.

**Comment by davideschiavone** [comment]
I commented line 134 of this PR with the following:

> 
> 
> 
> Hello @Silabs-ArjanB , thanks for your PR. Shall we maybe remove the exc_pc and trap_base_addr at line 133 and 134 and add them in the default statement?
> We should also probably not assign them to 0 as it may add another level of complexity. I would assign them to { trap_base_addr, 8'h0 } and m_trap_base_addr_i respectively.
> 
> What do you think?
>

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone , your proposal is better / cheaper indeed; I will do a new commit

**Comment by Silabs-ArjanB** [comment]
Hi @davideschiavone I did the fix you asked for. Weirdly enough I cannot see anywhere that you left a review comment. One warning here: Hello World works, but the 'firmware test' is broken because of the usage of old style CSRs related to performance counters inside stats.c. I am assuming that this is already fixed in some other pull request.

**Comment by davideschiavone** [comment]
> 
> 
> Hi @davideschiavone I did the fix you asked for. Weirdly enough I cannot see anywhere that you left a review comment. One warning here: Hello World works, but the 'firmware test' is broken because of the usage of old style CSRs related to performance counters inside stats.c. I am assuming that this is already fixed in some other pull request.

We do not want to maintain them here. They will be removed. Here we maintain only hello world

**Pull request merged**
