### PR TITLE
Updated Debug and Trigger documentation in user manual

### PR DESCRIPTION
**Pull request by silabs-PaulZ**
Signed-off-by: Paul Zavalney <paul.zavalney@silabs.com>

### CODE REVIEW

**Comment by jm4rtin** [comment]
As far as I know there is no debug triggers in the core. Is there a pending change to add those? If not, why are the trigger registers being added to the documentation?

**Comment by silabs-PaulZ** [comment]
Hi John, 
We did briefly discuss this HW breakpoint feature in a meeting, but I should have first put it as a pending issue before making a pull request. So yes, this is a request to add the Trigger feature (the same implementation as seen on IBEX).

**Comment by davideschiavone** [comment]
Hello @silabs-PaulZ , thanks a lot for the PR.
Can you also add the new CSR registers to the  `Table` 7: Control and Status Register Map` please?

Also, are these CSRs optional (controlled by a parameter like in Ibex) or always present?

Thanks
Davide

**Comment by davideschiavone** [comment]
Thanks @silabs-PaulZ !!! Merged it!

**Pull request merged**
